# Generated by Django 4.1.4 on 2022-12-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produc',
            new_name='Product',
        ),
    ]
