# Generated by Django 4.1.4 on 2022-12-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_slider_description_feature_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
