# Generated by Django 4.1.4 on 2022-12-15 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='rank',
        ),
    ]
